### ISSUE TITLE
صفحه سوم 

### ISSUE THREAD

**Issue by hosseinakbarpour** [aminalinjad/1000site#3]
https://finder.createx.studio/car-finder-single.html
این لینک اصلی صفحه است

**Comment by hosseinakbarpour** [comment]
Email me price drops and new listings for these search results:
جای این بخش توی همون سایز با همون کادر مپ بیاد لطفا

**Comment by hosseinakbarpour** [comment]
https://themes.getbootstrap.com/preview/?theme_id=92316
تا بالای عکس ها این مواردی که تا بالای عکس توی این صفحه اومده بیاد 
دکمه ایفنو و ریویو به همون شکل قرار بگیره مستقیم اسکرول شه بره همونجا

**Comment by hosseinakbarpour** [comment]
https://themes.getbootstrap.com/preview/?theme_id=92316
ریویو دقیقا به همین شکل طراحی بشه که توی این صفحه است اما پایین همون صفحه یعنی صفحه جدیدی باز نشه براش

**Comment by hosseinakbarpour** [comment]
تمامی دکمه ها لطفا عین همین صفحات طراحی بشه

**Comment by hosseinakbarpour** [comment]
https://finder.createx.studio/car-finder-single.html
قسمت سمت راست که ثابت میمونه سمت چپ تکون میخوره تا پایین صفحه که برای ریویو هست ادامه پیدا بکنه لطفا

**Comment by hosseinakbarpour** [comment]
https://themes.getbootstrap.com/preview/?theme_id=92316
مپ و باکس اینفو دقیقا شبیه به این صفحه باشه در صورتی که اسکرول چینش عکس ها و اطلاعات شبیه به کار سرچ یا لینکی که بک گراند مشکی داره باشه لطفا

**Comment by hosseinakbarpour** [comment]
لطفا ساجسشن های پایین صفحه هم در نظر بگیرید

**Comment by hosseinakbarpour** [comment]
https://finder.createx.studio/car-finder-single.html
قسمت سمت راست که ثابت میمونه سمت چپ تکون میخوره تا پایین صفحه که برای ریویو هست ادامه پیدا بکنه لطفا 
این مورد که ستون سمت چپ اسکرول نشه ستون سمت راست اسکرول بشه

**Comment by hosseinakbarpour** [comment]
روی ایکون های گالری جزییات نظرات بالای عکس کیلیک میکنیم اسکرول بشه بره همون جای صفحه

**Comment by hosseinakbarpour** [comment]
روی خود عکس کیلیک میکنیم عکس تمام صفحه بشه نشون داده بشه

**Comment by hosseinakbarpour** [comment]
ثابت موندن ستون سمت چپ صفحه رعایت نشده لطفا مد نظر قرار بگیره قثط ستون سمت راست اسکرول بشه

**Comment by hosseinakbarpour** [comment]
لطفا در اولین باکس سمت چپ که شماره تماس نمایش داده میشه سه تا ایکون شبکه های اجتماعی، رو بروی اسم و عکس هم تعداد بازدید ها از این صفحه و لایک و شیر قرار بگیره یدونه تیک وری فای هم برامون بذارید لطفا هم چنین سمت راست زیر باکس ارسال پیام یه خط ساعت باز و بسته بودن اونجا رو قرار بدید.

**Comment by aminalinjad** [comment]
> روی خود عکس کیلیک میکنیم عکس تمام صفحه بشه نشون داده بشه

همچین موردی اشتباه و امکان پذیر نیس 
یا شما میگید اسلایدر میخواید یا گالری ترکیب این دو تا امکان پذیر نخواهد بود

**Comment by aminalinjad** [comment]
> 
این هم انجام شده لطفا توضیح بدید چجوری باشه
